version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..." 
  build:
    commands:
      - echo "Forcing failure for demo"
      - exit 1   # This line makes the build fail
artifacts:
  files:
    - '**/*'
