version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Build started on date"
      - echo "Building the application..."
      - exit 1   # <-- Deliberate failure here
artifacts:
  files:
    - '/*'
